nodeLinker: node-modules

injectEnvironmentFiles: '.env'
npmScopes:
  jsswpt:
    npmRegistryServer: 'https://npm.pkg.github.com'
    npmAlwaysAuth: true
    npmAuthToken: ${GITHUB_TOKEN}
npmPublishRegistry: 'https://npm.pkg.github.com'
